name: Deploy API

on:
  workflow_dispatch:   # Manual trigger
  push:
    tags:
      - 'v*'          # Optional: run on version tags like v1.0, v2.1.3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish API project
        run: dotnet publish Bagile/Bagile.Api/Bagile.Api.csproj -c Release -o output

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: output
