services:
  bagile-api:
    container_name: bagile-api
    image: ghcr.io/asbrown77/bagile-api:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - config/api.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - shared
      - bagile-net

  bagile-etl:
    container_name: bagile-etl
    image: ghcr.io/asbrown77/bagile-etl:latest
    restart: unless-stopped
    env_file:
      - config/etl.env
    networks:
      - default
      - bagile-net

  bagile-portal:
    container_name: bagile-portal
    image: ghcr.io/asbrown77/bagile-portal:latest
    restart: unless-stopped
    ports:
      - "3100:3000"
    env_file:
      - config/portal.env
    networks:
      - default
      - shared

  bagile-pa:
    container_name: bagile-pa
    image: ghcr.io/asbrown77/bagile-pa:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - config/pa.env
    networks:
      - default
      - bagile-net

networks:
  shared:
    external: true
  bagile-net:
    external: true
