services:
  bagile-pa:
    container_name: bagile-pa
    image: ghcr.io/asbrown77/bagile-pa:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - config/pa.env
    depends_on:
      - postgres

  postgres:
    container_name: bagile-db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bagile
      POSTGRES_PASSWORD: bagile123
      POSTGRES_DB: bagile
    volumes:
      - bagile-data:/var/lib/postgresql/data
      - ./db/migrations:/scripts

volumes:
  bagile-data:
